apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud
  template:
    metadata:
      labels:
        app: fraud
    spec:
      containers:
        - name: fraud
          image: fraud:2.0.0
          ports:
            - containerPort: 8002
          # env:
          #   - name: EUREKA_SERVICE_URL
          #     value: http://eureka:8761
          #   - name: POSTGRES_SERVICE_URL
          #     value: http://postgres:5432

---
apiVersion: v1
kind: Service
metadata:
  name: fraud
spec:
  selector:
    app: fraud
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: LoadBalancer

