apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: customer-scale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: customer
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
        log: "The average utilization is {{ .AverageUtilization }}. The target value is {{ .Target }}."

# kubectl top pods
# kubectl get hpa
